version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6380:6379"
    restart: always

  postgres-db:
    container_name: postgres-db-doctor
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"
      TZ: "America/Sao_Paulo"
    ports:
      - "5433:5432"
    networks:
      - postgres-db-doctor
    restart: always

  pgadmin:
    container_name: pgadmin4PT
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15433:80"
    networks:
      - postgres-db-doctor

networks:
  postgres-db-doctor:
    driver: bridge